/*
FORM-LOGIN
*/
export const MODIFICA_EMAIL = "MODIFICA_EMAIL";
export const MODIFICA_SENHA = "MODIFICA_SENHA";
export const MODIFICA_NOME = "MODIFICA_NOME";

export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const REGISTER_USER_REQUESTED = "REGISTER_USER_REQUESTED";

export const ADD_CONTACT_EMAIL_MODIFIED = "ADD_CONTACT_EMAIL_MODIFIED";

export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";

