/*
FORM-LOGIN
*/
export const MODIFICA_EMAIL = "MODIFICA_EMAIL";
export const MODIFICA_SENHA = "MODIFICA_SENHA";
export const MODIFICA_NOME = "MODIFICA_NOME";

export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
